name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm ci  # Install dependencies from package-lock.json

      - name: Build the app
        run: npm run build  # Build the React app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master  # The branch where the built app will be deployed
          folder: build  # Folder containing the build output
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for deployment
